name: Docker build and push
on:
  push:
    branches:
      - master
jobs:

  test:
     runs-on: self-hosted

     steps:
       - name: Print Message
         run: echo "Running test job here"


  docker:
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::5}" >> $GITHUB_ENV
      
      - name: Build Docker image
        run:  |
           docker build -t hit52/ci-demo-app:$SHORT_SHA .

      - name: Push Docker image
        run: |
          docker push hit52/ci-demo-app:$SHORT_SHA
